configuration:
  activeRevisionsMode: Single
  ingress:
    external: true
    targetPort: 3333
template:
  containers:
  - image: ghcr.io/esn-tumi/app/server:main
    name: tumi-server
    env:
    - name: DATABASE_URL
      secretRef: database-url
    - name: NODE_ENV
      value: production
    - name: VERSION
      value: GIT_VERSION
    - name: HIVE_TOKEN
      secretRef: hive-token
    - name: SENDGRID_API_KEY
      secretRef: sendgrid-key
    - name: AUTH0_SECRET
      secretRef: auth0-secret
    - name: STRIPE_KEY
      secretRef: stripe-key
    - name: STRIPE_WH_SECRET
      secretRef: stripe-wh-secret
    - name: PM2_PUBLIC_KEY
      value: 9itltnqk9yqwqph
    - name: PM2_SECRET_KEY
      secretRef: pm2-secret-key
    - name: BLOB_SAS_TOKEN
      secretRef: azure-storage-token
    - name: PRODUCT_SAS_TOKEN
      secretRef: azure-product-storage-token
    - name: PHOTO_SAS_TOKEN
      secretRef: photo-storage-token
    - name: STORAGE_CONNECTION_STRING
      secretRef: storage-connection-string
    - name: FULL_TAX_RATE
      secretRef: full-tax-rate
    - name: REDUCED_TAX_RATE
      secretRef: reduced-tax-rate
    - name: VISION_KEY
      secretRef: vision-key
    resources:
      cpu: 1
      memory: 2Gi
  scale:
    minReplicas: 0
    maxReplicas: 5
    rules:
    - name: http-rule
      http:
        metadata:
          concurrentRequests: 100
